const assert = require("node:assert/strict")
const fs = require("node:fs")

const app = fs.readFileSync("src/App.tsx", "utf8")
const login = fs.readFileSync("src/components/ui/modern-stunning-sign-in.tsx", "utf8")
const admin = fs.readFileSync("src/components/AdminDashboard.tsx", "utf8")
const adminApi = fs.readFileSync("netlify/functions/admin-overview.mts", "utf8")
const migration = fs.readFileSync("supabase/migrations/001_tributo_leve_saas.sql", "utf8")
const plansMigration = fs.readFileSync("supabase/migrations/006_planos_periodicos_demo.sql", "utf8")
const registration = fs.readFileSync("netlify/functions/register-user.mts", "utf8")
const css = fs.readFileSync("src/styles.css", "utf8")
const html = fs.readFileSync("index.html", "utf8")
const manifest = JSON.parse(fs.readFileSync("public/site.webmanifest", "utf8"))

assert.match(html, /src\/main\.tsx/)
assert.match(html, /Manrope/)
assert.match(app, /ProfileStep/)
assert.match(app, /CreditsStep/)
assert.match(app, /Comparison/)
assert.match(app, /Timeline/)
assert.match(app, /Technical/)
assert.match(login, /Ative seu acesso/)
assert.match(login, /FALLBACK_PLANS/)
assert.match(login, /Testar demonstração gratuita/)
assert.match(admin, /Salvar preço/)
assert.match(adminApi, /update_plan_price/)
assert.match(migration, /product_id uuid references public\.products/)
assert.match(migration, /profiles_cpf_hash_unique/)
assert.match(migration, /cpf_already_registered/)
assert.match(plansMigration, /pro-trimestral/)
assert.match(plansMigration, /company_limit/)
assert.match(registration, /email_confirm: true/)
assert.match(registration, /validCpf/)
assert.match(css, /@media \(max-width: 700px\)/)
assert.match(css, /prefers-reduced-motion/)
assert.equal(manifest.display, "standalone")

const labelTargets = [...app.matchAll(/<Field id="([^"]+)" label=/g)].map((match) => match[1])
assert(labelTargets.length >= 10, "A aplicação deve manter labels explícitos nos campos")
assert(!/[—–]/.test(`${app}${login}`), "Travessões não devem aparecer no texto da interface")

console.log(`OK: React app validado com ${labelTargets.length} grupos de campos rotulados`)
